# Site settings
title: GBG São José dos Campos
email: gbgsjc@gmail.com
description: GBG São José dos Campos.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gbgsjc.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
